# Generated by Django 4.0.1 on 2022-01-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_team', models.CharField(max_length=100)),
                ('winning_score', models.CharField(max_length=50)),
                ('losing_team', models.CharField(max_length=50)),
                ('losing_score', models.CharField(max_length=50)),
                ('draw', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(choices=[('CARDINALS', 'Arizona Cardinals'), ('FALCONS', 'Atlanta Falcons'), ('RAVENS', 'Baltimore Ravens'), ('BILLS', 'Buffalo Bills'), ('BILLS', 'Carolina Panthers'), ('BEARS', 'Chicago Bears'), ('PANTHERS', 'Carolina Panthers'), ('BENGALS', 'Cincinnati Bengals'), ('BROWNS', 'Cleveland Browns'), ('COWBOYS', 'Dallas Cowboys'), ('BRONCOS', 'Denver Broncos'), ('LIONS', 'Detriot Lions'), ('PACKERS', 'Green Bay Packers'), ('TEXANS', 'Houston Texans'), ('COLTS', 'Indianapolis Colts'), ('JAGUARS', 'Jacksonville Jaguars'), ('CHIEFS', 'Kansas City Chiefs'), ('RAIDERS', 'Las Vegas Raiders'), ('CHARGERS', 'Los Angeles Chargers'), ('RAMS', 'Los Angeles Rams'), ('DOLPHINS', 'Miami Dolphins'), ('VIKINGS', 'Minnesota Vikings'), ('PATRIOTS', 'New England Patriots'), ('SAINTS', 'New Orleans Saints'), ('GIANTS', 'New York Giants'), ('JETS', 'New York Jets'), ('EAGLES', 'Philadelphia Eagles'), ('49ERS', 'San Francisco 49ers'), ('SEATTLE', 'Seattle Seahakws'), ('BUCS', 'Tampa Bay Buccaneers'), ('TITANS', 'Tennessee Titans'), ('REDSKINS', 'Washington Football Team')], max_length=50)),
            ],
        ),
    ]
