# Generated by Django 4.0.1 on 2022-01-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
