# Generated by Django 4.0.1 on 2022-01-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
