# Generated by Django 4.0.1 on 2022-01-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
