# Generated by Django 4.0.1 on 2022-01-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_games_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
