# Generated by Django 4.0.1 on 2022-01-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
