# Generated by Django 4.0.1 on 2022-01-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
