# Generated by Django 4.0.1 on 2022-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_delete_games_alter_teams_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_team', models.CharField(max_length=100)),
                ('winning_score', models.CharField(max_length=50)),
                ('losing_team', models.CharField(max_length=50)),
                ('losing_score', models.CharField(max_length=50)),
                ('draw', models.BooleanField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
