# Generated by Django 4.0.1 on 2022-01-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='draw',
        ),
    ]
