# Generated by Django 4.0.1 on 2022-01-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_remove_games_draw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
