# Generated by Django 4.0.1 on 2022-01-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
