# Generated by Django 4.0.1 on 2022-01-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
