# Generated by Django 4.0.1 on 2022-01-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
