# Generated by Django 4.0.1 on 2022-02-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
