# Generated by Django 4.0.1 on 2022-02-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Baltimore Ravens', 'Baltimore Ravens'), ('Buffalo Bills', 'Buffalo Bills'), ('Carolina Panthers', 'Carolina Panthers'), ('Chicago Bears', 'Chicago Bears'), ('Carolina Panthers', 'Carolina Panthers'), ('Cincinnati Bengals', 'Cincinnati Bengals'), ('Cleveland Browns', 'Cleveland Browns'), ('Dallas Cowboys', 'Dallas Cowboys'), ('Denver Broncos', 'Denver Broncos'), ('Detroit Lions', 'Detroit Lions'), ('Green Bay Packers', 'Green Bay Packers'), ('Houston Texans', 'Houston Texans'), ('Indianapolis Colts', 'Indianapolis Colts'), ('Jacksonville Jaguars', 'Jacksonville Jaguars'), ('Kansas City Chiefs', 'Kansas City Chiefs'), ('Las Vegas Raiders', 'Las Vegas Raiders'), ('Los Angeles Chargers', 'Los Angeles Chargers'), ('Los Angeles Rams', 'Los Angeles Rams'), ('Miami Dolphins', 'Miami Dolphins'), ('Minnesota Vikings', 'Minnesota Vikings'), ('New England Patriots', 'New England Patriots'), ('New Orleans Saints', 'New Orleans Saints'), ('New York Giants', 'New York Giants'), ('New York Jets', 'New York Jets'), ('Philadelphia Eagles', 'Philadelphia Eagles'), ('San Francisco 49ers', 'San Francisco 49ers'), ('Seattle Seahakws', 'Seattle Seahakws'), ('Tampa Bay Buccaneers', 'Tampa Bay Buccaneers'), ('Tennessee Titans', 'Tennessee Titans'), ('Washington Football Team', 'Washington Football Team')], max_length=100),
        ),
    ]
